spring.application.name=restaurante
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#Temporario
spring.security.user.name=admin
spring.security.user.password=admin

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.threads.virtual.enabled=true

pagamento.api.url=${PAGAMENTO_API_URL}
